[package]
name = "nft"
version = "1.0.0"
edition = "2024.beta"
authors = ["Amaitari Philip (amaitariphilip@gmail.com)"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
nft = "0x0"
